<?php

namespace EspritEntreAide\SpottedBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function seif($idp){


        return $this->createQueryBuilder('a')
            ->select('COUNT(a)')
            ->setParameter('idPublication', $idp)
            ->getQuery()
            ->getSingleScalarResult();
    }


    public function countComments()
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT c FROM EspritEntreAide\SpottedBundle\Entity\Commentaire c ")
        ;


        // returns an array of Product objects
        return $query->getResult();
    }




}
