<?php

namespace EspritEntreAide\SpottedBundle\Repository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{
    public function rankingspotted()
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT p  FROM EspritEntreAide\SpottedBundle\Entity\Rating p ORDER BY p.rating DESC")
            ->setMaxResults(9)
        ;


        // returns an array of Product objects
        return $query->getResult();
    }
}
