<?php

namespace EspritEntreAide\AnnonceBundle\Repository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    public function countAnnonce($var){

        try {
            return $this->createQueryBuilder('a')
                ->select('COUNT(a)')
                ->where("a.categorieA LIKE :var")
                ->setParameter('var', $var)
                ->getQuery()
                ->getSingleScalarResult();
        } catch (NoResultException $e) {
        } catch (NonUniqueResultException $e) {
        }
    }
    public  function rechercheAjax($ser){
        return $this->createQueryBuilder('o')
            ->where('o.titreA LIKE  :ser')
            ->setParameter('ser', '%' . $ser . '%')
            ->getQuery()
            ->getResult();
    }
    public function findAnnonoces()
    {
        return $this->createQueryBuilder('o')
            ->getQuery()
            ->setMaxResults(5)

            ->getResult();




    }

}
