<?php

namespace EspritEntreAide\ClubBundle\Repository;

/**
 * ClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubRepository extends \Doctrine\ORM\EntityRepository
{

    public  function rechercheAjax($ser){
        return $this->createQueryBuilder('o')
            ->where('o.nomC LIKE  :ser')
            ->setParameter('ser', '%' . $ser . '%')
            ->getQuery()
            ->getResult();
    }
}
