<?php

namespace EspritEntreAide\ClubBundle\Repository;

/**
 * membreclubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class membreclubRepository extends \Doctrine\ORM\EntityRepository
{
}
