<?php

namespace EspritEntreAide\EvenementBundle\Repository;

/**
 * GoogleMapsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoogleMapsRepository extends \Doctrine\ORM\EntityRepository
{
}
